### ISSUE TITLE
What is the license of irqstat?

### ISSUE THREAD

**Issue by yangoliver** [lanceshelton/irqstat#1]
Hi,

Thanks for sharing this powerful tool.

What is the license of irqstat?

This tool does help us a lot on debugging NUMA interrupts related problems.
We want to include this tool into our commercial products for debugging support.
However, there is no license information. I understand the tool is simple and small, but having a license information would be very helpful for making the decision.

Could you add LICENSE file into this project? 

We can determine next step per legal evaluations.

Thanks.

**Comment by lanceshelton** [comment]
Hi Oliver,

I am glad irqstat is helpful to you, and would like for it to be available
for you to use.  Let me think about it for a day and I'll decide on a
license and update the project.

Lance

**Comment by yangoliver** [comment]
Lance,

I consulted with our lawyer and got confirmed that GPLv3 is not encouraged to be used in our product.

Our Linux distribution is using many other popular Licesnse like: GP:Lv2, BSD and so on.

Anyway, you are the owner, our legal team will review our request after you determine it.

**Comment by lanceshelton** [comment]
Hi Oliver,

irqstat is now licensed under the MIT license.  It is similar to a BSD license.

Lance
