### ISSUE TITLE
Need have version information for irqstat

### ISSUE THREAD

**Issue by yangoliver** [lanceshelton/irqstat#2]
Currently, irqstat doesn't define any version information.

Could we define a version/release information?

How about add irqstat -v or --version option as well?

**Comment by lanceshelton** [comment]
Versioned, tagged, and released.

To get version info:
    irqstat -v
or
    irqstat --version

Please use this release:
https://github.com/lanceshelton/irqstat/releases/tag/v1.0.0

It is available for download as a .tar:
https://github.com/lanceshelton/irqstat/releases/download/v1.0.0/irqstat-v1.0.0.tar

Let me know if that is good enough for now.

**Comment by yangoliver** [comment]
Thanks for your prompt response.

It looked good to me.
